services:
  web:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      # - "3000:3000"  # Expose port 3000 for local access
      - "127.0.0.1:3000:3000" # Bind to localhost only
    volumes:
      - .:/app  # Mount the current directory to the container
      - /app/node_modules